openapi: 3.0.0
info:
  title: LMS
  description: All Endpoints for LMS Collection
  version: 1.0.0
servers:
  - url: http://{{base_url}}
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /books:
    get:
      tags:
        - default
      summary: Get books
      description: Returns a list of all books
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Add book
      description: Adds a book to the books list
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                Author: Author2
                ISBN: '9789007792'
                Published_Year: 2004
                title: Book2
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /books/9789007792:
    put:
      tags:
        - default
      summary: Update book
      description: Updates a book by ISBN
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                Published_Year: 2023
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /books/9789007790:
    delete:
      tags:
        - default
      summary: Delete Book
      description: Deletes a book by ISBN
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /books/search:
    get:
      tags:
        - default
      summary: Search for book
      description: Search for book
      security:
        - bearerAuth: []
      parameters:
        - name: Author
          in: query
          schema:
            type: string
          example: Author1
        - name: Genre
          in: query
          schema:
            type: string
          example: Fiction
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}